### ISSUE TITLE
Loading 최적화

### ISSUE THREAD

**Issue by sewonkimm** [soyoungjeong/EmojiByEternal#18]
프로그램 실행 할 때 로딩 시간이 2~3초가량 너무 오래 걸립니다 😢

**Comment by sewonkimm** [comment]
[InnerHTML 문제](https://ruru.tistory.com/entry/innerHTML-%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A0-%EB%95%8C-%EC%86%8D%EB%8F%84%EB%A5%BC-%EC%9C%84%ED%95%9C-%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD)

**Comment by sewonkimm** [comment]
수정했으나 로딩 속도에 별 차이 없음

**Comment by doong-jo** [comment]
각각의 아이콘들을 직접 svg로 가지고 있어야 할 것 같습니다

**Comment by doong-jo** [comment]
getEmoji에서 가져오는 것 같은데, 싱글 스레드로 처리하기보다는 webworker를 생성해서 동기적으로 불러들여야 할 것 같습니다.

**Comment by sewonkimm** [comment]
[chrome clipboard api](https://developer.chrome.com/apps/clipboard)를 활용해 불필요한 라이브러리 로딩 줄이기

**Comment by sewonkimm** [comment]
twemoji 라이브러리 사용으로 인해 야기되는 성능저하를 image sprite로 최적화하기
