### ISSUE TITLE
copy시 undefined문제 

### ISSUE THREAD

**Issue by soyoungjeong** [soyoungjeong/EmojiByEternal#19]
copy기능을 할 때 recent 부분을 너무 빨리 누르다보면 undefined가 복사될 때가 있습니다. 
recent를 로드 하기 전에 클릭을 해서 이런 현상이 발생하는 듯 합니다.

**Comment by sewonkimm** [comment]
![image](https://user-images.githubusercontent.com/30452963/64103093-54114e00-cdac-11e9-954f-e83a08f5a5cd.png)

캡쳐에 표시한 영역을 클릭하면 undefined 복사되는 것으로 확인 했습니다.
