### ISSUE TITLE
북마크 클릭 관련

### ISSUE THREAD

**Issue by soyoungjeong** [soyoungjeong/EmojiByEternal#2]
북마크 아이콘 클릭 후 다른 북마크 아이콘 선택했을 때
이전에 클릭한 아이콘 색이 그대로 보라색입니다. 
- [ ] 다시 회색으로 돌아가도록 수정

**Comment by sewonkimm** [comment]
![image](https://user-images.githubusercontent.com/30452963/63223692-cdc60b00-c1f4-11e9-9749-9a9673ffa9e7.png)

확장앱으로 test 할 때에는 스타일이 적용되서 해당 이슈가 없습니다🙂
