### ISSUE TITLE
Emoji 크기가 비정상으로 큰 경우가 있습니다.

### ISSUE THREAD

**Issue by doong-jo** [soyoungjeong/EmojiByEternal#21]
최초에 실행 시는 잘됐는데 새로고침 이후 발생했습니다.
(설정에서 크기도 Normal로 되어있었습니다.)

![스크린샷 2019-09-02 오후 9 43 29](https://user-images.githubusercontent.com/22005861/64115531-dad52380-cdca-11e9-9383-6a2bd3f2653e.png)

**Comment by sewonkimm** [comment]
getEmoji.js에서 attachEmoji이후에 size를 설정해 주는 함수를 추가할 예정입니다. 감사합니다 🙂

**Comment by sewonkimm** [comment]
확장앱 첫 설치후  버그 발생
