### ISSUE TITLE
github discription 내용 변경과 웹사이트 추가 요청

### ISSUE THREAD

**Issue by sewonkimm** [soyoungjeong/EmojiByEternal#37]
github discription 내용 변경과 웹사이트 추가 요청합니다!

`discription`
네이버 웨일 브라우저 확장앱 - 모지모지 이모지

`website`
https://store.whale.naver.com/detail/ilglkcbgchmaadclmokfkcdmnanniakn

변경방법
![](https://i.imgur.com/CexeWBQ.gif)

**Comment by soyoungjeong** [comment]
수정했습니다 ~!
