### ISSUE TITLE
오타수정 건의사항입니다!

### ISSUE THREAD

**Issue by JaeHyeonKim19** [soyoungjeong/EmojiByEternal#39]
이모지를 복사하는 버튼을 클릭해서 복사가 되었을 때 버튼에 coped라고 전시되네요! 왠지 copied를 쓰시려다가 오타가난 것 같네요! 확인 부탁드려요.

**Comment by sewonkimm** [comment]
오타 확인하여 업데이트에 반영했습니다. 감사합니다~👍
