### ISSUE TITLE
이모지 빈칸

### ISSUE THREAD

**Issue by soyoungjeong** [soyoungjeong/EmojiByEternal#4]
![네모칸1](https://user-images.githubusercontent.com/26589909/63345510-ddc52280-c38d-11e9-8bf0-baeccf7bef8c.png)
![빈칸1](https://user-images.githubusercontent.com/26589909/63345511-ddc52280-c38d-11e9-863f-7c501e56d0d6.png)

- 빈칸이거나 네모칸인 공간이 있습니다.

**Comment by sewonkimm** [comment]
![image](https://user-images.githubusercontent.com/30452963/63352422-0e13bd80-c39c-11e9-80b0-9b4679289f2a.png)

제 컴퓨터에서는 잘 나오는데... 왜 그럴까요...?
