### ISSUE TITLE
copy 관련 업데이트 해야 할 부분

### ISSUE THREAD

**Issue by sewonkimm** [soyoungjeong/EmojiByEternal#6]
[copy PR](https://github.com/soyoungjeong/EmojiByEternal/pull/5) 참조

**Comment by sewonkimm** [comment]
- [ ] Multie Auto-copy Function
- [ ] Copy button -> Status button
- [x] input CSS scroll
- [ ] input reset

**Comment by Siromom** [comment]
input CSS scroll
기존 코드: 이모티콘을 클릭하면 span에 붙여넣기했음.
수정 코드: <span id="copy_group">을  <input>으로 변경 value에 값 넣어줌.

**Comment by soyoungjeong** [comment]
- Copy button -> Status button
정확히 어떤 기능인가요?!

**Comment by sewonkimm** [comment]
현재 copy 동작
1. emoji click
2. copy button click 

emoji를 click 했을 때 2번 과정을 거치지 않아도 클립보드에 복사 되어야합니다.

copy button 기능은 2가지가 되어야합니다.
1. 클립보드에 emoji가 복사 되었을 때, 'copied' 상태 표시
2. copy button을 click하면 클립보드에 input 내용 복사

**Comment by soyoungjeong** [comment]
> * [x]  Multie Auto-copy Function
> * [x]  Copy button -> Status button
> * [x]  input CSS scroll
> * [x]  input reset

**Comment by soyoungjeong** [comment]
> * [x]  Multie Auto-copy Function
> * [x]  Copy button -> Status button
> * [x]  input CSS scroll
> * [x]  input reset
